version: '3'
services:
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db_files:/data/db

  gpt_wrapper:
    build: .
    depends_on:
      - mongo_db
      - weaviate
    env_file:
      - .env.development

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.18.4
    ports:
      - 8080:8080
    restart: on-failure:0
    environment:
      OPENAI_APIKEY: $OPENAI_TOKEN
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,generative-openai'
      CLUSTER_HOSTNAME: 'node1'
