version: '3'
services:
  mongo_db:
    image: mongo
    ports:
      - "27028:27017"
    volumes:
      - ./db_files:/data/db

  gpt_wrapper:
    build: .
    depends_on:
      - mongo_db
    env_file:
      - .env.development
