version: '3'
services:
  mongo_tow:
    image: mongo
    ports:
      - "27028:27017"
    volumes:
      - ./db_files:/data/db
    env_file:
      - .env.development

  tow:
    build: .
    depends_on:
      - mongo_tow
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src
      - ./images:/app/images
